{% set version = "1.3.1" %}
{% set name = "zlib" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/madler/zlib/releases/download/v{{ version }}/zlib-{{ version }}.tar.gz
    folder: src
    sha256: 9A93B2B7DFDAC77CEBA5A558A580E74667DD6FEDE4585B91EEFB60F03B72DF23

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}	# [win]
    - make               	# [unix]
