{% set version = "1.3.1" %}
{% set name = "zlib" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/madler/zlib/releases/download/v{{ version }}/zlib-{{ version }}.tar.gz
    folder: .
    sha256: 9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23

requirements:
  build:
    - {{ compiler('cxx') }}	# [win]
    - make               	# [unix]

about:
  home: https://www.zlib.net/
  license: zlib License
  summary: A software library used for data compression as well as a data format